-- Conky generado por matugen — NO editar a mano, se sobreescribe con cada wallpaper
conky.config = {
    alignment = 'top_right',
    background = true,
    update_interval = 1,
    double_buffer = true,
    no_buffers = true,
    text_buffer_size = 2048,
    own_window = true,
    own_window_type = 'desktop',
    own_window_colour = '#00000000',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    gap_x = 30,
    gap_y = 50,
    minimum_width = 220,
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,
    use_xft = true,
    font = 'JetBrainsMono Nerd Font:size=9',
    xftalpha = 0.9,
    uppercase = false,
    default_color = '{{colors.on_background.default.hex}}',
    color1 = '{{colors.primary.default.hex}}',
    color2 = '{{colors.secondary.default.hex}}',
    color3 = '{{colors.tertiary.default.hex}}',
    color4 = '{{colors.outline.default.hex}}',
};

conky.text = [[
${font JetBrainsMono Nerd Font:size=34:bold}${color1}${time %H:%M}${font}
${color4}${hr 1}
${font JetBrainsMono Nerd Font:size=10}${color2}${time %A, %d de %B}${font}
${voffset 10}
${color3}  ${color}󰈀 subida  ${alignr}${upspeed ${gw_iface}}
${color3}  ${color}󰈂 bajada  ${alignr}${downspeed ${gw_iface}}
${voffset 8}
${color1}  ${color}DISCO  ${alignr}${fs_used /} / ${fs_size /}
${fs_bar /}
${voffset 8}
${color2}  uptime ${alignr}${color}${uptime_short}
${color2}  kernel ${alignr}${color}${kernel}
${voffset 8}
]];
