# Generado por matugen — NO editar a mano, se sobreescribe con cada wallpaper
# Paleta Material You aplicada a kitty (reemplaza current-theme.conf)

foreground #f1dedd
background #1a1111
selection_foreground #571e1c
selection_background #ffb3ae

cursor #ffb3ae
cursor_text_color #1a1111

url_color #e1c28c

active_border_color #ffb3ae
inactive_border_color #534342
bell_border_color #ffb4ab
visual_bell_color none

wayland_titlebar_color #534342
macos_titlebar_color #534342

active_tab_foreground #f1dedd
active_tab_background #5d3f3d
inactive_tab_foreground #f1dedd
inactive_tab_background #534342
tab_bar_background #534342
tab_bar_margin_color none

mark1_foreground #571e1c
mark1_background #ffb3ae
mark2_foreground #442927
mark2_background #e7bdb9
mark3_foreground #402d04
mark3_background #e1c28c

# Los 16 colores ANSI básicos
color0 #1a1111
color8 #a08c8a
color1 #ffb4ab
color9 #ffb4ab
color2 #ffb3ae
color10 #ffb3ae
color3 #e1c28c
color11 #e1c28c
color4 #e7bdb9
color12 #e7bdb9
color5 #733330
color13 #733330
color6 #5d3f3d
color14 #5d3f3d
color7 #f1dedd
color15 #571e1c